service: hero-api-aws

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  httpApi:
    cors: true
  environment:
    DYNAMO_TABLE_NAME: ${self:custom.heroTableName}
    REGION: ${self:provider.region}
    BUCKET_NAME: ${self:custom.bucketName}
    BUCKET_NAME_UPLOAD: ${self:custom.bucketNameUpload}
    EXCEL_FOLDER: ${self:custom.excelFolder}
    PDF_FOLDER: ${self:custom.pdfFolder}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.heroTableName}"
custom:
  heroTableName: Heroes-Table${self:provider.stage}
  bucketName: data-heroes
  bucketNameUpload: testpayroll
  excelFolder: xlsxFolder
  pdfFolder: pdfFolder

plugins:
  - serverless-iam-roles-per-function
functions:
  getHero:
    handler: hero/get.getHero
    name: getHero
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: hero/{id}
          method: GET
          cors: true
  createHero:
    handler: hero/create.createHero
    name: createHero
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: hero/create
          method: POST
          cors: true
  updateHero:
    handler: hero/update.updateHero
    name: updateHero
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: hero
          method: PUT
          cors: true
  deleteHero:
    handler: hero/delete.deleteHero
    name: deleteHero
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: hero/{id}
          method: DELETE
          cors: true
  listHeroes:
    handler: hero/list.listHeroes
    name: getlistHeroes
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: heroes
          method: GET
          cors: true
  listHeroesExcel:
    handler: hero/excelList.listHeroesExcel
    name: getExcelHeroes
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: heroesExcel
          method: GET
          cors: true
  listHeroesPdf:
    handler: hero/pdfList.listHeroesPdf
    name: get-pdf-heroes
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: heroesPdf
          method: GET
          cors: true
  uploadfile:
    handler: hero/uploadfile.uploadfile
    name: uploadfile
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: hero/uploadfile
          method: POST
          cors: true
resources:
  Resources:
    HerosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.heroTableName}
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
