service: hero-crud-aws

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    DYNAMO_TABLE_NAME: ${self:custom.heroTableName}
    REGION: ${self:provider.region}
    BUCKET_NAME: ${self:custom.bucketName}
    EXCEL_FOLDER: ${self:custom.excelFolder}
    PDF_FOLDER: ${self:custom.pdfFolder}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.heroTableName}"
custom:
  heroTableName: Heroes-Table${self:provider.stage}
  bucketName: data-heroes
  excelFolder: xlsxFolder
  pdfFolder: pdfFolder
  serverless-offline:
    location: .webpack/service
  bundle:
    sourcemaps: false
    copyFiles:
      - from: "node_modules/chrome-aws-lambda/bin/aws.tar.br"
        to: "./bin"
      - from: "node_modules/chrome-aws-lambda/bin/chromium.br"
        to: "./bin"
      - from: "node_modules/chrome-aws-lambda/bin/swiftshader.tar.br"
        to: "./bin"
  headers:
    - Content-Type
plugins:
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-bundle
functions:
  getHero:
    handler: hero/get.getHero
    name: get-hero-v1
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: hero/{id}
          method: GET
          cors: true
  createHero:
    handler: hero/create.createHero
    name: create-hero-v1
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: hero/create
          method: POST
          cors: true
  updateHero:
    handler: hero/update.updateHero
    name: update-Hero-v1
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: hero
          method: PUT
          cors: true
  deleteHero:
    handler: hero/delete.deleteHero
    name: delete-hero-v1
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: hero/{id}
          method: DELETE
          cors: true
  listHeroes:
    handler: hero/list.listHeroes
    name: get-list-heroes
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: heroes
          method: GET
          cors: true
  listHeroesExcel:
    handler: hero/excelList.listHeroesExcel
    name: get-excel-heroes
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: heroesExcel
          method: GET
          cors: true
  listHeroesExcel:
    handler: hero/pdfList.listHeroesPdf
    name: get-pdf-heroes
    memorySize: 128
    timeout: 20
    events:
      - http:
          path: heroesPdf
          method: GET
          cors: true        
resources:
  Resources:
    HerosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.heroTableName}
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
